collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.886172
color:
  saturation: 0.4907251
  brandStrength: 0.8187184
  lightness: 0.5
  brandColors:
    - '#FFFFFF'
    - '#D8BEA3'
    - '#1F0C04'
    - '#776478'
    - '#9A271F'
  rhythmicContrast: 0.4822934
layout_spectrum: 0.2394604
name: Tina Foster
