layout_spectrum: 0.2394604
color:
  saturation: 0.4907251
  lightness: 0.5
  brandStrength: 0.2676678
  brandColors:
    - '#FAFCFD'
    - '#1F1530'
    - '#775C6E'
    - '#CF6E5C'
    - '#AC0B0D'
  rhythmicContrast: 0.4822934
typography_spectrum: 0.8878583
name: Tina Foster
